name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.3.4
  - ca-certificates=2018.4.16
  - certifi=2018.4.16
  - conda=4.5.4
  - flake8=3.5.0
  - mccabe=0.6.1
  - openssl=1.0.2o
  - pep8=1.7.1
  - pycodestyle=2.3.1
  - pyflakes=1.6.0
  - asn1crypto=0.24.0
  - cffi=1.11.5
  - chardet=3.0.4
  - conda-env=2.6.0
  - cryptography=2.2.2
  - idna=2.6
  - libcxx=4.0.1
  - libcxxabi=4.0.1
  - libedit=3.1
  - libffi=3.2.1
  - ncurses=6.0
  - pip=9.0.3
  - pycosat=0.6.3
  - pycparser=2.18
  - pyopenssl=17.5.0
  - pysocks=1.6.8
  - python=3.6.5
  - python.app=2
  - readline=7.0
  - requests=2.18.4
  - ruamel_yaml=0.15.35
  - setuptools=39.0.1
  - six=1.11.0
  - sqlite=3.23.1
  - tk=8.6.7
  - urllib3=1.22
  - wheel=0.31.0
  - xz=5.2.3
  - yaml=0.1.7
  - zlib=1.2.11


