name: strecenv
channels:
- conda-forge
- defaults
dependencies:
- affine
- fiona
- gdal
- h5py
- impactutils
- ipython
- jupyter
- libcomcat
- mapio
- numpy
- obspy
- openpyxl
- pandas
- pyproj
- pytest
- pytest-cov
- python=3.5
- rasterio
- shapely
- xlrd
- xlwt

