name: strecenv
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.1
  - asn1crypto=0.24.0
  - atomicwrites=1.1.5
  - attrs=18.1.0
  - backcall=0.1.0
  - beautifulsoup4=4.6.0
  - blas=1.1
  - bleach=2.1.3
  - boost=1.66.0
  - boost-cpp=1.66.0
  - boto3=1.7.36
  - botocore=1.10.37
  - bzip2=1.0.6
  - ca-certificates=2018.4.16
  - cairo=1.14.10
  - cartopy=0.16.0
  - certifi=2018.4.16
  - cffi=1.11.5
  - chardet=3.0.4
  - click=6.7
  - click-plugins=1.0.3
  - cligj=0.4.0
  - coverage=4.5.1
  - cryptography=2.2.1
  - curl=7.60.0
  - cycler=0.10.0
  - dbus=1.13.0
  - decorator=4.3.0
  - docutils=0.14
  - entrypoints=0.2.3
  - et_xmlfile=1.0.1
  - expat=2.2.5
  - fiona=1.7.12
  - fontconfig=2.12.6
  - freetype=2.8.1
  - freexl=1.0.5
  - future=0.16.0
  - gdal=2.2.4
  - geos=3.6.2
  - geotiff=1.4.2
  - gettext=0.19.8.1
  - giflib=5.1.4
  - glib=2.55.0
  - gmp=6.1.2
  - gst-plugins-base=1.8.0
  - gstreamer=1.8.0
  - h5py=2.8.0
  - hdf4=4.2.13
  - hdf5=1.10.1
  - html5lib=1.0.1
  - icu=58.2
  - idna=2.6
  - impactutils=0.8.6
  - ipykernel=4.8.2
  - ipython=6.4.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.2.1
  - jdcal=1.4
  - jedi=0.12.0
  - jinja2=2.10
  - jmespath=0.9.3
  - jpeg=9b
  - json-c=0.12.1
  - jsonschema=2.6.0
  - jupyter=1.0.0
  - jupyter_client=5.2.3
  - jupyter_console=5.2.0
  - jupyter_core=4.4.0
  - kealib=1.4.7
  - kiwisolver=1.0.1
  - krb5=1.14.6
  - libcomcat=1.2.4
  - libdap4=3.18.3
  - libffi=3.2.1
  - libgdal=2.2.4
  - libiconv=1.15
  - libkml=1.3.0
  - libnetcdf=4.6.1
  - libpng=1.6.34
  - libpq=9.6.3
  - libsodium=1.0.16
  - libspatialite=4.3.0a
  - libssh2=1.8.0
  - libtiff=4.0.9
  - libxcb=1.13
  - libxml2=2.9.8
  - libxslt=1.1.32
  - lxml=4.2.1
  - mapio=0.7.8
  - markupsafe=1.0
  - matplotlib=2.2.2
  - mistune=0.8.3
  - more-itertools=4.2.0
  - munch=2.3.2
  - nbconvert=5.3.1
  - nbformat=4.4.0
  - ncurses=5.9
  - notebook=5.5.0
  - numpy=1.14.4
  - obspy=1.1.0
  - olefile=0.45.1
  - openblas=0.2.20
  - openjpeg=2.3.0
  - openpyxl=2.5.4
  - openssl=1.0.2o
  - owslib=0.16.0
  - pandas=0.23.1
  - pandoc=2.2.1
  - pandocfilters=1.4.2
  - paramiko=2.4.1
  - parso=0.2.1
  - pcre=8.41
  - pexpect=4.6.0
  - pickleshare=0.7.4
  - pillow=5.1.0
  - pip=9.0.3
  - pixman=0.34.0
  - pluggy=0.6.0
  - poppler=0.61.1
  - poppler-data=0.4.9
  - proj4=4.9.3
  - prompt_toolkit=1.0.15
  - ptyprocess=0.5.2
  - py=1.5.3
  - pyasn1=0.4.3
  - pycparser=2.18
  - pycrypto=2.6.1
  - pyepsg=0.3.2
  - pygments=2.2.0
  - pynacl=1.1.2
  - pyopenssl=18.0.0
  - pyparsing=2.2.0
  - pyproj=1.9.5.1
  - pyqt=5.6.0
  - pyshp=1.2.12
  - pysocks=1.6.8
  - pytest=3.6.1
  - pytest-cov=2.5.1
  - python=3.5.5
  - python-dateutil=2.7.3
  - pytz=2018.4
  - pyzmq=17.0.0
  - qt=5.6.2
  - qtconsole=4.3.1
  - rasterio=0.36.0
  - readline=7.0
  - requests=2.18.4
  - s3transfer=0.1.13
  - scipy=1.1.0
  - send2trash=1.5.0
  - setuptools=39.2.0
  - shapely=1.6.4
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.11.0
  - snuggs=1.4.1
  - sqlalchemy=1.2.8
  - sqlite=3.20.1
  - terminado=0.8.1
  - testpath=0.3.1
  - tk=8.6.7
  - tornado=5.0.2
  - traitlets=4.3.2
  - urllib3=1.22
  - wcwidth=0.1.7
  - webencodings=0.5
  - wheel=0.31.0
  - widgetsnbextension=3.2.1
  - xerces-c=3.2.0
  - xlrd=1.1.0
  - xlsxwriter=1.0.5
  - xlwt=1.3.0
  - xorg-libxau=1.0.8
  - xorg-libxdmcp=1.1.2
  - xz=5.2.3
  - zeromq=4.2.5
  - zlib=1.2.11
  - bcrypt=3.1.4
  - libgcc=7.2.0
  - libgcc-ng=7.2.0
  - libgfortran=3.0.0
  - libstdcxx-ng=7.2.0
  - util-linux=2.21
